nodeLinker: pnp

plugins:
  - checksum: 3ed9da5dcfb491b6387791023bd12a763e1fc7b23692d8291bbde6bc4306e07473994bce919bcf26ee4538ba9c0745a7970d4eeac7ce66fcc1d7a700b66190ed
    path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js"
