CREATE TABLE source (
  source_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE source_item (
  source_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  amount         VARCHAR(16),
  unit           VARCHAR(16),
  source_id      INTEGER NOT NULL REFERENCES source(source_id)
                  ON UPDATE RESTRICT
                  ON DELETE RESTRICT
);

CREATE TABLE tastes (
  tastes_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  source_id  INTEGER NOT NULL REFERENCES source(source_id)
               ON UPDATE RESTRICT
               ON DELETE RESTRICT
);

CREATE INDEX idx_source_item_source_id ON source_item(source_id);
CREATE INDEX idx_tastes_source_id ON tastes(source_id);

CREATE INDEX idx_source_name ON source(name);
CREATE INDEX idx_source_item_name ON source_item(name);
CREATE INDEX idx_tastes_name ON tastes(name);
